version: '3.8'

services:
  # Basit Jitsi Meet Web Server
  jitsi-web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./jitsi-web:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped

  # Basit WebRTC Server (Node.js)
  webrtc-server:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./webrtc-server:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    restart: unless-stopped
